env:
  global:
    - secure: "a/uyfxeCoDUhXfCDhhibIXOYpWXhio3SgiN/upfJDN+KFf8xNvs/b1TUotbWKCVjssMHNS5RvRVr2UUOC4Rg/Qxfrea7pYRyU6aBbtCLzP7hKoE4rJWPSgLOmkpmO7Q47KDrUesy3G5cyMhpp65PzSUyOkpOXQi8lrb4/JA5Wi4="
language: java
jdk:
  - openjdk7
  - oraclejdk7
services:
  - redis-server
after_success:
  - mvn cobertura:cobertura coveralls:cobertura
addons:
  coverity_scan:
    project:
      name: "gresrun/jesque"
      description: "Build submitted via Travis CI"
    notification_email: gresrun@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
